import type { Metadata } from "next";

import "./globals.css";
import ThemeProvider from "@/utilities/ThemeProvider";

export const metadata: Metadata = {
  title: "Pixcel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-rose-600`}>
        <ThemeProvider attribute={"class"} defaultTheme={"dark"}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
